language: node_js
sudo: required
branches:
  only:
    - master
    - canary
cache:
  yarn: true

before_install:
  - npm install --global yarn@1.10.1
before_script:
  - yarn bootstrap

script:
  - yarn build
  - yarn test:cov
    
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - bash publish-canary.sh
    on:
      branch: canary
  - provider: script
    skip_cleanup: true
    script:
      - echo "RELEASING STABLE"
    on:
      branch: master
