language: node_js
sudo: required
branches:
  only:
    - master
    - canary
cache:
  yarn: true


before_install:
  - npm install --global yarn@1.10.1
before_script:
  - yarn bootstrap

jobs:
  include:
    - stage: Build and Run Test Coveralls
      script: 
        - yarn build
        - yarn test:cov
    - stage: Release
      script:
        - yarn build
      deploy:
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^canary|master$
        provider: script
        skip_cleanup: true
        script:
          - echo "RELEASING"

